# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull_apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: mkdir
        run: |
          mkdir -p ./headless-browser/out
          chmod 777 ./headless-browser/out

      - name: run docker
        run: docker compose -f headless-browser/docker-compose.yml up -d --wait
      
      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run the download script
        run: node selenium-dl.js

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      # - name: debug out
      #   run: ls -laR ./headless-browser/

      # - name: debug docker
      #   run: docker compose -f ./headless-browser/docker-compose.yml logs

      # - name: debug file server
      #   run: curl http://localhost:8080/

      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: obsidian-apk
          path: ./headless-browser/out/

  unpack_apk:
    needs: pull_apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: fetch apk
        uses: actions/download-artifact@v3
        with:
          name: obsidian-apk
          
      - name: rename apk to something simple
        run: mv *.apk obsidian.apk

      - name: pull apktool docker image
        run: docker pull ghcr.io/ibotpeaches/apktool:latest

      - name: unpack the apk
        run: docker run --rm -ti -v $PWD/:/workdir -w /workdir ghcr.io/ibotpeaches/apktool:latest d obsidian.apk

      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: obsidian-unpacked
          path: ./obsidian/

