# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull_apk:
    runs-on: ubuntu-latest

    container: 
      image: node:latest
      volumes:
        - apk-out:/out

    services:
      firefox:
        image: selenium/standalone-chrome:latest
        env:
          START_XVFB: "false"
        ports:
          - 4444
        volumes:
          - apk-out:/out
        options: >-
          --cpus 2
          --memory 4096m
          --shm-size=2gb
          --health-cmd="stat /etc/passwd || exit 1"
          --health-interval=2s

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run the download script
        run: node selenium-dl.js

      - name: debug out
        run: ls -la /out/

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: obsidian-apk
          path: /out
