# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull_apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: mkdir
        run: mkdir -p ./headless-browser/out

      - name: run docker
        run: docker compose -f headless-browser/docker-compose.yml up -d --wait
      
      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run the download script
        run: node selenium-dl.js ./headless-browser/out/

      - name: debug out
        run: ls -laR ./headless-browser/

      - name: debug docker
        run: docker compose -f ./headless-browser/docker-compose.yml logs

      # - name: Save artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: obsidian-apk
      #     path: /out
