version: '3'
services:
  firefox:
    image: selenium/standalone-chrome:latest
    env:
      START_XVFB: "false"
    ports:
      - 4444:4444
    volumes:
      - ./out:/out
    healthcheck:
      test: ["CMD-SHELL", "stat /etc/passwd || exit 1"]
      interval: 2s